name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/ClipSnap/ClipSnap.sln

    - name: Build
      run: dotnet build src/ClipSnap/ClipSnap.sln --configuration Release --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ClipSnap-build
        path: src/ClipSnap/ClipSnap/bin/Release/net8.0-windows/
        retention-days: 7
